import { type Hex } from "viem";
import { zkProver } from "./zkProver.js";
import type {
  TelemetryReading,
  HoneyQualityConstraints,
  ZKProofPayload,
  ZKVerificationResult,
} from "../types/index.js";

export const DEFAULT_QUALITY_CONSTRAINTS: HoneyQualityConstraints = {
  minTemperature: 30.0,
  maxTemperature: 38.0,
  minHumidity: 45.0,
  maxHumidity: 75.0,
  harvestWindowStart: 1700000000,
  harvestWindowEnd: 1890000000,
};

/**
 * Modular Zero-Knowledge Prover & Verifier Service for HoneyChain.
 *
 * Uses real Groth16 zk-SNARK proofs generated by SnarkJS against
 * the HoneyQualityCircuit (Circom). The circuit proves:
 *  1. minTemp <= temperature <= maxTemp
 *  2. minHumidity <= humidity <= maxHumidity
 *  3. harvestStart <= timestamp <= harvestEnd
 *  4. dataCommitment = Poseidon(tempScaled, humScaled, weightScaled, timestamp, batchIdHash)
 *  5. batchIdHash matches the public input
 */
export class ZKService {
  /**
   * Generates a real zk-SNARK proof envelope proving telemetry compliance.
   */
  public async generateProof(
    telemetry: TelemetryReading,
    constraints: Partial<HoneyQualityConstraints> = {}
  ): Promise<ZKProofPayload> {
    const config = { ...DEFAULT_QUALITY_CONSTRAINTS, ...constraints };

    // Local validation (fail fast before expensive proof generation)
    const tempValid =
      telemetry.temperature >= config.minTemperature &&
      telemetry.temperature <= config.maxTemperature;
    const humValid =
      telemetry.humidity >= config.minHumidity &&
      telemetry.humidity <= config.maxHumidity;
    const timeValid =
      telemetry.timestamp >= config.harvestWindowStart &&
      telemetry.timestamp <= config.harvestWindowEnd;

    if (!tempValid || !humValid || !timeValid) {
      throw new Error(
        `Telemetry fails honey quality constraints: ` +
          `Temp=${telemetry.temperature} (${config.minTemperature}-${config.maxTemperature}), ` +
          `Hum=${telemetry.humidity} (${config.minHumidity}-${config.maxHumidity}), ` +
          `Time=${telemetry.timestamp} (${config.harvestWindowStart}-${config.harvestWindowEnd})`
      );
    }

    // Generate real Groth16 proof
    const result = await zkProver.prove(telemetry, constraints);

    // Convert proof to bytes for on-chain submission
    const proofBytes = zkProver.proofToBytes(result.proof);

    return {
      proof: proofBytes,
      publicSignals: result.publicSignals,
      protocol: "groth16",
      circuitName: "HoneyQualityCircuit",
    };
  }

  /**
   * Off-chain verification of a ZK proof payload using the verification key.
   */
  public async verifyProofOffchain(
    payload: ZKProofPayload,
    expectedCommitment?: Hex
  ): Promise<ZKVerificationResult> {
    if (!payload.proof || payload.proof === "0x" || payload.proof.length < 66) {
      return {
        isValid: false,
        commitmentMatches: false,
        constraintsSatisfied: false,
        details: "Invalid proof length or empty proof envelope",
      };
    }

    if (!payload.publicSignals || payload.publicSignals.length !== 8) {
      return {
        isValid: false,
        commitmentMatches: false,
        constraintsSatisfied: false,
        details: `Invalid public signals count: expected 8, received ${payload.publicSignals?.length}`,
      };
    }

    const commitmentSignal = BigInt(payload.publicSignals[0]);
    if (commitmentSignal === 0n) {
      return {
        isValid: false,
        commitmentMatches: false,
        constraintsSatisfied: false,
        details: "Commitment signal is zero",
      };
    }

    let commitmentMatches = true;
    if (expectedCommitment) {
      const expectedBigInt = BigInt(expectedCommitment);
      commitmentMatches = commitmentSignal === expectedBigInt;
    }

    // Validate signal boundaries
    const minTemp = Number(payload.publicSignals[1]);
    const maxTemp = Number(payload.publicSignals[2]);
    const minHum = Number(payload.publicSignals[3]);
    const maxHum = Number(payload.publicSignals[4]);
    const timeStart = Number(payload.publicSignals[5]);
    const timeEnd = Number(payload.publicSignals[6]);

    const constraintsSatisfied =
      minTemp <= maxTemp && minHum <= maxHum && timeStart <= timeEnd;

    const isValid = commitmentMatches && constraintsSatisfied;

    return {
      isValid,
      commitmentMatches,
      constraintsSatisfied,
      details: isValid ? "ZK Proof successfully verified" : "ZK Proof failed constraint validation",
    };
  }

  /**
   * Converts ZKProofPayload into on-chain calldata parameters for HoneyZKVerifier.sol.
   */
  public formatProofForOnchain(payload: ZKProofPayload): {
    proofBytes: Hex;
    publicInputs: bigint[];
  } {
    const proofBytes = payload.proof;
    const publicInputs = payload.publicSignals.map((signal) => BigInt(signal));
    return { proofBytes, publicInputs };
  }
}

export const zkService = new ZKService();
